### ISSUE TITLE
Related to https://github.com/xmidt-org/webpa-common/issues/1045

### ISSUE THREAD

**Issue by krshna-dtdl** [xmidt-org/webpa-common#1046]
@denopink The load on current Talaria is just of 5 Routers as its for a testing environment. Still we are getting this issue.

**Comment by denopink** [comment]
Just a reminder, there isn't a magic solution to this because it depends on your infra and how your xmidt cluster is setup.

A timeout means talaria's response to the request from scytales is taking too long.

Have you confirmed talaria is receiving the request from scytale? If not, try running your talaria server with a `DEBUG` logging level.

If see logs indicating talaria is receiving the requests from scytale, feel free to post logs here.

But, if you don't see any logs indicating talaria is receiving the requests from scytale, then something in your stack is causing the timeout before it reaches talaria. At that point, I would suggest reaching out to your infra team/provider or ops running the testing environment for help figuring out the issue on your side.

**Comment by krshna-dtdl** [comment]
@denopink Yes the request went to talaria

At talaria we are getting: Could not process device request

Will post more logs soon
