### ISSUE TITLE
Add more information to the Connect event

### ISSUE THREAD

**Issue by Symbianx** [xmidt-org/webpa-common#271]
After looking at the logs of talaria we were able to see some really valuable information when a device connects to the server, information called the `convey` payload. Fields like `boot-time` and `hw-last-reboot-reason` are included in the log. [This is the log I am talking about](https://github.com/Comcast/webpa-common/blob/bd4c644760d8d708804f87461c513271c046de4a/device/manager.go#L158).

In terms of analytics and quality of service metrics all this information would be really useful for us. Is this something you would be willing to add?

Thanks in advance
Miguel Alexandre
NOS Inovação

**Comment by schmidtw** [comment]
Good suggestion!  We added the information from the convey header to the logs to start with so that log processors can grab the information and make it available somewhat.  On the metrics front, the concern we have is the unbounded set of data that it represents.

https://prometheus.io/docs/practices/naming/#labels

It may make sense to identify/design an interface to something like redis that allows some state-full data to be gathered/reported upon outside the normal production data flow.

**Comment by Symbianx** [comment]
The concern about prometheus is extremely valid.

We thought about it and we think it would be really awesome if the convey data was incorporated in the `operational` event (which already exists) and sent to all the webhook listeners, this way the listeners could take more complex and intelligent decisions based on the event.
This solution would also take the responsability of saving the data (like you said, with redis for instance) out from talaria into a service responsible for just that.

**Comment by kristinaspring** [comment]
@schmidtw @Symbianx can this issue be closed?
