### ISSUE TITLE
Prune the types package

### ISSUE THREAD

**Issue by johnabass** [xmidt-org/webpa-common#424]
The types package is a relic and should be removed.  There are a few places this type is used, and we should change the code to use idiomatic `golang`.

**Comment by joe94** [comment]
@johnabass the `Duration` type (and only one) within the `types` package seems to have been created as a custom JSON encoder/decoder so that json values show a more human readable value vs the nanoseconds one that the default encoder provides.

Were you thinking the idiomatic way forward is just to drop this type and use the default encoder?
