### ISSUE TITLE
Ambiguous import issue

### ISSUE THREAD

**Issue by j-mai** [xmidt-org/webpa-common#536]
There seems to be a problem with hashicorp 1.7.0 that results in an ambiguous import error:

```
github.com/xmidt-org/webpa-common/service/consul imports
        github.com/hashicorp/consul/api: ambiguous import: found package github.com/hashicorp/consul/api in multiple modules:
        github.com/hashicorp/consul v1.4.2 
        github.com/hashicorp/consul/api v1.7.0
```

Workaround is to add this line to `go.mod`:
`github.com/hashicorp/consul v1.7.0`

Make sure to not do `go mod tidy` afterwards because the line will go away if you do.

**Comment by kristinaspring** [comment]
I originally solved a consul dependency issue in https://github.com/xmidt-org/webpa-common/pull/525, but it was reintroduced when wepba-common started importing argus (which was importing an older version of wepba-common with the consul issue).  I bumped wepba-common in [this argus commit](https://github.com/xmidt-org/argus/commit/402fede05764f2a0cd520b7495fb845ee4ebf372), so once we import this commit or something past it, this issue is solved.
