### ISSUE TITLE
Changes related to new Ancla Version

### ISSUE THREAD

**Issue by utsavbatra5** [xmidt-org/webpa-common#572]
On upgrading to ancla v0.1.3-0.20210316223809-833bddb2dc0e that has the changes for opentelemetry, we are now facing issue in webpa common. In service/consul/datacenterWatch.go , we are getting error in call to chrysom.NewClient() as logger is not passed to the same as per its new signature. 

We would like to pass the logger from the context. The only solution that i have been able to figure out is inject the Getlogger function(having context) from each microservice where servicecfg.NewEnvironment() is called. This would need a change in each microservice where NewEnvironment() is being called. 

Do you suggest any better solution for the same?

FYI: The call to servicecfg.NewEnvironment() can be found in main.go of caduceus, talaria, scytale etc.

**Comment by joe94** [comment]
Hey @utsavbatra5, since the datacenter watch code only uses the chrysom client to listen for changes, the context logger wouldn't be used. So, it's fine to just pass nil as the `getLogger` function in this case.
Sources:

https://github.com/xmidt-org/webpa-common/blob/main/service/consul/datacenterWatch.go#L85
https://github.com/xmidt-org/argus/blob/main/chrysom/client.go#L373

**Comment by utsavbatra5** [comment]
All right Joe. I just released a new PR https://github.com/xmidt-org/webpa-common/pull/573. Kindly review the same.
