### ISSUE TITLE
Claims Validation Error

### ISSUE THREAD

**Issue by schmidtw** [xmidt-org/webpa-common#62]
If you pass in a nasty claim you can bypass the protection.

`/api/v2/device/mac:112233445566/stat?ignore-me=/api/v2/device/mac:112233445566/hook`
or
`/api/v2/device/mac:112233445566/stat/../../../../../api/v2/device/mac:112233445566/hook`

**Comment by ilawjr** [comment]
This issue is still valid.

**Comment by kristinaspring** [comment]
Closing this issue, but will investigate and possibly open a new one in the bascule repo.

**Comment by kristinaspring** [comment]
This is still an issue in the `basculechecks` package:
https://github.com/xmidt-org/webpa-common/blob/master/basculechecks/basculechecks.go#L59

instead of matching anywhere in the string, we need to be more judicious about how we are matching, to ensure the requester is authorized to access the endpoint.

**Comment by kristinaspring** [comment]
The first case is dealt with from using the URL EscapedPath() function, which doesn't include parameters:
https://golang.org/pkg/net/url/#URL.EscapedPath

Still working on a fix for the second case and making our regex more picky.

**Comment by kristinaspring** [comment]
Going to see what more needs to be done for this issue, if anything.

**Comment by kristinaspring** [comment]
This issue has been fixed.
